name: Changelog

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run
        env:
          GITHUB_TOKEN: ${{ secrets.XOR_C }}
        run: |
          #pip install git
          python .github/scripts/change.py

      - name: Commit and push
        run: |
          git config --global user.name "HATRED54"
          git config --global user.email "HATRED54@github.com"
          git add .
          git commit -m "UPDATE CHANGELOG.MD"
          git push origin main