name: CMake

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Verify build directory
        run: |
          cd build
          dir build

#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: windows-build
#          path: build/asm-analyze
