name: CMake

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
            build-type: RelWithDebInfo
            path: Debug\asm-analyze.exe
            artifact-name: asm-analyze-win

          - name: macOS
            os: macos-latest
            path: build
            artifact-name: asm-analyze-macos

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

  package:
    name: Package build
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.matrix.config.artifact-name }}
          path: ${{ steps.build.matrix.config.path }}
