name: CMake

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          cmake --build .

#      - name: Verify build directory
#        run: |
#          ${{ matrix.os }} == 'windows-latest' && dir /a build/asm-analyze || ls -la build/asm-analyze

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: build/asm-analyze

      - name: Post-build workflow dispatch
        uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: .github/workflows/post-build.yml
